### ISSUE TITLE
疼痛表單數值調整拉桿狀態紀錄問題

### ISSUE THREAD

**Issue by eenvil** [NYCU-Service-Learning/nanao-system#1]
疼痛表單填寫 第一個選項的數值調整拉桿，調整完數值後，在選擇 cancel 時，再點選另一個部位，會保留上次填寫的數值。選擇ok會重設到0，應改為顯示目前狀態的數值。

**Comment by eenvil** [comment]
fixed with commit id:
7b6aab957761d0d2e88a0b6d44a0192fa694cede

**Comment by eenvil** [comment]
waiting for main to merge
@chou-ting-wei

**Comment by chou-ting-wei** [comment]
finish merge yaya
