### ISSUE TITLE
前後端帳號名稱及密碼檢查

### ISSUE THREAD

**Issue by scottchou1018** [NYCU-Service-Learning/nanao-system#12]
帳號名稱和密碼都是空的仍可新增帳號，需做檢查。

**Comment by chou-ting-wei** [comment]
15bf326 已解決

**Comment by chou-ting-wei** [comment]
https://github.com/NYCU-Service-Learning/nanao-system/commit/15bf326403ec914ff045cb29707937eca76493c0 已解決
